# Prettier friendly markdownlint config (all formatting rules disabled)
extends: markdownlint/style/prettier
# Heading levels should only increment by one level at a time
MD001: false
# Multiple headings with the same content
MD024: false
# Multiple top-level headings in the same document
MD025: false
# Bare URL used
MD034: false
# Emphasis used instead of a heading
MD036: false
